### PR TITLE
Use a queue to speed up packet processing

### PR DESCRIPTION
**Pull request by mundya**
Rather than immediately routing packets to filters add them to a queue for later processing. This reduces the time taken to remove packets from the network, consequently it reduces the number of dropped packets.

---

 - [ ] Add a more informative commit message
 - [x] Do better than defaulting to a fixed queue size?
 - [x] More thorough testing
 - [ ] How to report "dropped" [unqueued] packets?

### CODE REVIEW

**Comment by mundya** [comment]
> How to report "dropped" [unqueued] packets?

Could report the count in SDRAM (possibly the SV struct?). This probably should be combined with the simulator recording the number of dropped packets as well.

**Comment by neworderofjamie** [comment]
PyNN SpiNNaker has a region where we just shove various counters like this
(spin1 API task queue overruns and various application-specific counters) -
it just requires the c++ code to enumerate the counters and the python to
give them some labels and do something sensible with them. Another area of
commonality?

**Comment by mundya** [comment]
- [x] Update the DTCM constraints in the operators which are partitioned to account for the amount used to store the queue.

**Comment by neworderofjamie** [comment]
Looks good to me

**Comment by mundya** [comment]
Reporting dropped/unqueued packets should be a later PR. @neworderofjamie we should discuss what commonality there is.

**Pull request merged**
