### PR TITLE
Fix connections from pass nodes to Nodes

### PR DESCRIPTION
**Pull request by mundya**
Connections between passthrough Nodes and regular Nodes were ignored by
mistake. This commit resolves this issue (#22).

### CODE REVIEW

**Comment by mundya** [comment]
@celiasmith, this should fix #22. I've rebased this to include the binaries in the repository, could you try an install from GitHub and see if this fixes your problem please?

**Comment by tcstewar** [comment]
Looks good to me....  :)

**Comment by celiasmith** [comment]
Works great, thanks! :rainbow:

**Comment by mundya** [comment]
Awesome, thank you :smile:

**Pull request merged**
