### PR TITLE
Fix malloc_or_die

### LINKED ISSUE #102: MALLOC_AND_DIE doesn't
The MALLOC_AND_DIE calls in c_main don't cause it to die - spin1_exit just turns off the interrupts, all subsequent allocations continue to fail and the core goes into watchdog

### PR DESCRIPTION
**Pull request by mundya**
Calls RT_ERROR to kill the core after a malloc fails.

Fixes #102.

### CODE REVIEW

**Comment by mundya** [comment]
Are you happy with this @neworderofjamie?

**Comment by neworderofjamie** [comment]
I think using rt_malloc would be better :)

**Comment by mundya** [comment]
> I think using rt_malloc would be better :)

Is that a thing? Which version of SpiNNaker tools is it in?

**Comment by neworderofjamie** [comment]
definitely in the version of rig I am using - there's a whole bunch of
error codes

**Comment by mundya** [comment]
Huh? As in the RT code it raises should be RT_MALLOC?

**Comment by neworderofjamie** [comment]
Yep, I think several of these could be useful
https://github.com/project-rig/rig/blob/master/rig/machine_control/consts.py#L246-L267

**Comment by mundya** [comment]
Oohhh... I see, I thought you meant there was a "rt_malloc" function. Yeah, I'll swap out "RT_ABORT".

**Pull request merged**
