### PR TITLE
Merged SpiNNaker tools

### PR DESCRIPTION
**Pull request by neworderofjamie**

### CODE REVIEW

**Comment by mundya** [comment]
Thank you!

**Comment by mundya** [comment]
Need to modify the `clear` rule as well, thanks @neworderofjamie.

**Comment by neworderofjamie** [comment]
This would benefit from a similar addition to this:

https://github.com/project-rig/pynn_spinnaker/commit/6e2c97fdb176e083e0794f0f13b31b9605c30541

**Comment by mundya** [comment]
Thanks for looking at this @neworderofjamie!

**Comment by mundya** [comment]
@rowleya - We have now tested nengo_spinnaker with the merged `spinnaker_tools` and everything seems good, thanks.

**Comment by rowleya** [comment]
Excellent!

**Pull request merged**
