### PR TITLE
Change fixpoint

### PR DESCRIPTION
**Pull request by mundya**
- [x] Remove magic fixpoint code
- [x] Switch fixpoint representations to something with more fractional bits (~~S8.23 or S6.25 for now~~ S12.19)

### CODE REVIEW

**Comment by mundya** [comment]
``` python
with nengo.Network() as network:
    step = nengo.Node([1.0, -0.4])
    probe = nengo.Probe(step, synapse=nengo.LinearFilter([1.0], [0.001, 0.11, 1.0]))
```

Before:
lti

After:
lti_new

**Comment by mundya** [comment]
@tcstewar - does this change to the representational range seem reasonable to you? It's not as savage as I'd wanted but small ensembles have LARGE decoder components. I think a future plan is to assess where some scaling could be applied to improve the numerics, but that might be for a later/post-thesis-written day.

**Comment by mundya** [comment]
Hmm, I'm getting a lot of saturated values in a cconv network I'm testing, so this may still be too big a change to the fixed point format.

**Comment by tcstewar** [comment]
> does this change to the representational range seem reasonable to you? It's not as savage as I'd wanted but small ensembles have LARGE decoder components. I think a future plan is to assess where some scaling could be applied to improve the numerics, but that might be for a later/post-thesis-written day.

Definitely seems like a step in the right direction, but I'm wondering whether different parts of the system might need different ranges.  Or even maybe a `small_ensemble` that uses 15,16 and a `large_ensemble` that uses 5.26.  Or maybe having an ensemble shift everything down by round(log2(n_neurons)).  Not sure what the easy things are to try here....

**Comment by mundya** [comment]
I was hoping to avoid different ranges, but yeah, might be necessary :/

**Pull request closed without merging**
